### ISSUE TITLE
Add REST service

### ISSUE THREAD

**Issue by consolethinks** [paulscherrerinstitute/scicat-cli#111]
Create a package that can spin up a REST service that makes it possible for users to pick and choose which datasets to ingest

- [ ] Pick an API description method (eg. OpenAPI)
- [ ] Research server libraries
- [ ] Define endpoints in the API description method
- [ ] With the generated bindings, develop the API

**Comment by sbliven** [comment]
Server libraries:
- standard lib. Requires boilerplate, but might be ok if generated from OpenAPI
- chi. Compatible with standard lib
- gin. Popular but not compatible with standard lib.

Please summarize in a confluence page.

**Comment by consolethinks** [comment]
This is moved to https://github.com/SwissOpenEM/Ingestor/issues/7
