### ISSUE TITLE
scicat-cli v4 backend support

### ISSUE THREAD

**Issue by consolethinks** [paulscherrerinstitute/scicat-cli#114]
adding support for the v4 backend, maybe as a separate branch?

**Comment by sbliven** [comment]
Working:
- datasetArchiver
- datasetIngestor


Untested (need PSI endpoints to test):
- deatasetRetriever
- datasetCleaner 
- publishedData/publishedDataRetrieve

**Comment by consolethinks** [comment]
Working:
- dataasetArchiver
- datasetGetProposal
- datasetIngestor
- globusCheckTransfer
- waitForJobFinished

Untested:
- datasetPublishData (might get deprecated)
- datasetPublishDataRetrieve (might get deprecated)
- datasetRetriever (partially works, it uses a constant prefix for datasets for some reason ["20.500.11935"])

Not working:
- datasetCleaner (missing "datablocks" endpoints)

**Comment by consolethinks** [comment]
Changes that were required in order to make the commands above work as intended with SciCat BE v4:
- For all endpoints, the access token has to be passed in the header and not as a URL parameter
- when creating an archival job, we must add an ownerGroup, unlike in v3. Currently it is set to the first accessGroup of the user.
- the `GET archivalJob` endpoint returns a slightly different json to represent jobs, so I adjusted scicat-cli accordingly
- v4 supports getting a job with a specific ID so no filtered searching is required to find it
- Added a proper `isValidDomain` regex check as the hostname must be an IANA compliant domain name in V4
- all tests that broke due to v4 changes have been adjusted
- when testing if the metadata is valid using the SciCat BE, the returned response object is slightly different to v3, for which code adjustments have been made in `CheckMetadataValidity` function
- In v4, there are no separate dataset endpoints for each type of dataset, they all use `/datasets`, code has been adjusted accordingly
- In some cases, the http code returned by the server is not just `200` anymore, could be 201, 202... etc. for which the code has been adjusted
- In v4, updating the lifecycle of the dataset (endpoint `PUT/PATCH /Datasets` uses the "PATCH" HTTP method instead of "PUT", code has 
- Whenever filtered search is used with API requests, the filter string is passed as a URL parameter instead of being put into the header, code has been adjusted for it
- the structs for creating jobs have changed in v4, for which the code has been adjusted
- `getUserInfoFromToken.go` was rewritten extensively as the `/Users/userInfos` isn't an endpoint in v4 anymore, with 2 requests to the endpoints `/users/my/self` and `/userindentites/findOne` are used to replicate the feature, as well as response structs were adjusted

Other changes:
- better error handling in places (removing the remainder of log fatals in the non-cli specific portions of the code)
- clean-up logging code: moved them to cli specific code
- general code clean-up
- added the local backend option to a few commands to be able to test them
- changed local_api_server string to reflect the one in scicatlive (backend.localhost instead of localhost:3000)
- replaced generic "strings.Replace" method with url.QueryEscape for converting url parameters 
- created separate Read and Check Metadata functions (by separating `ReadAndCheckMetadata` function) to be able to use them independently in code that imports the package (needed for Ingestor service as it will never read a `metadata.json` from file directly)
- removed some commented code
- `createFilter` has been adjusted to accept a string list to simplify calling code
